import 'package:flutter_application/features/budget/domain/entities/budget.dart';
import 'package:flutter_application/features/transactions/data/models/category_model.dart';

class BudgetModel extends Budget {
  const BudgetModel({
    required super.id,
    required super.userId,
    super.categoryId,
    super.category,
    required super.name,
    required super.amount,
    super.spentAmount,
    required super.period,
    required super.startDate,
    required super.endDate,
    required super.alertThreshold,
    required super.isActive,
  });

  factory BudgetModel.fromJson(Map<String, dynamic> json) {
    return BudgetModel(
      id: json['id'],
      userId: json['user_id'],
      categoryId: json['category_id'],
      category: json['categories'] != null ? CategoryModel.fromJson(json['categories']) : null,
      name: json['name'],
      amount: (json['amount'] as num).toDouble(),
      spentAmount: (json['spent_amount'] as num?)?.toDouble() ?? 0.0,
      period: json['period'],
      startDate: DateTime.parse(json['start_date']),
      endDate: DateTime.parse(json['end_date']),
      alertThreshold: json['alert_threshold'] ?? 80,
      isActive: json['is_active'] ?? true,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      // 'id': id, // Usually generated by DB
      'user_id': userId,
      'category_id': categoryId,
      'name': name,
      'amount': amount,
      'period': period,
      'start_date': startDate.toIso8601String(),
      'end_date': endDate.toIso8601String(),
      'alert_threshold': alertThreshold,
      'is_active': isActive,
    };
  }
}
