"""Sync models with existing tables v2

Revision ID: f959b802154d
Revises: f50e2eb8b106
Create Date: 2025-12-10 19:45:21.993987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f959b802154d'
down_revision = 'f50e2eb8b106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Cleanup orphan data before adding constraints
    op.execute("DELETE FROM savings_goals WHERE user_id NOT IN (SELECT id FROM users)")
    op.execute("DELETE FROM budgets WHERE user_id NOT IN (SELECT id FROM users)")
    op.execute("DELETE FROM transactions WHERE user_id NOT IN (SELECT id FROM users)")
    op.execute("DELETE FROM user_profiles WHERE id NOT IN (SELECT id FROM users)")
    op.execute("DELETE FROM virtual_portfolios WHERE user_id NOT IN (SELECT id FROM users)")
    op.execute("DELETE FROM chat_conversations WHERE user_id NOT IN (SELECT id FROM users)")
    
    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('icon',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('rarity',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'common'::text"))
        batch_op.alter_column('requirement_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('period',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index('idx_budgets_active')
        batch_op.drop_index('idx_budgets_dates')
        batch_op.drop_index('idx_budgets_user_id')
        batch_op.drop_constraint('budgets_category_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('budgets_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_constraint('categories_name_type_user_id_key', type_='unique')
        batch_op.drop_constraint('categories_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_profiles', ['user_id'], ['id'])

    with op.batch_alter_table('chat_conversations', schema=None) as batch_op:
        batch_op.alter_column('last_message_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index('idx_chat_conversations_user_id')
        batch_op.drop_constraint('chat_conversations_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_profiles', ['user_id'], ['id'])

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.alter_column('extracted_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('image_url',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='URL to the image uploaded by user or generated by AI',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index('idx_chat_messages_conversation_id')
        batch_op.drop_index('idx_chat_messages_created_at')
        batch_op.drop_constraint('chat_messages_conversation_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('chat_messages_transaction_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'chat_conversations', ['conversation_id'], ['id'])
        batch_op.create_foreign_key(None, 'transactions', ['transaction_id'], ['id'])

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('financial_insights', schema=None) as batch_op:
        batch_op.alter_column('suggested_actions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('related_transaction_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('analysis_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index('idx_financial_insights_read')
        batch_op.drop_index('idx_financial_insights_type')
        batch_op.drop_index('idx_financial_insights_user_id')
        batch_op.drop_constraint('financial_insights_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_profiles', ['user_id'], ['id'])

    with op.batch_alter_table('investment_challenges', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('requirement_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('requirement_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('difficulty',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'easy'::text"))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('savings_goals', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index('idx_savings_goals_user_id')
        batch_op.drop_constraint('savings_goals_user_id_key', type_='unique')
        batch_op.drop_constraint('savings_goals_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('spending_patterns', schema=None) as batch_op:
        batch_op.alter_column('top_categories',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('spending_trends',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('ai_recommendations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_constraint('spending_patterns_user_id_period_start_period_end_period_ty_key', type_='unique')
        batch_op.drop_constraint('spending_patterns_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_profiles', ['user_id'], ['id'])

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('transaction_type',
               existing_type=postgresql.ENUM('DEPOSIT', 'WITHDRAWAL', name='transactiontype'),
               nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('total_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index('idx_transactions_category_id')
        batch_op.drop_index('idx_transactions_date')
        batch_op.drop_index('idx_transactions_type')
        batch_op.drop_index('idx_transactions_user_date')
        batch_op.drop_index('idx_transactions_user_id')
        batch_op.drop_constraint('transactions_category_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('transactions_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('location')
        batch_op.drop_column('notes')
        batch_op.drop_column('longitude')
        batch_op.drop_column('ocr_raw_data')
        batch_op.drop_column('transaction_date')
        batch_op.drop_column('receipt_image_url')
        batch_op.drop_column('input_method')
        batch_op.drop_column('latitude')
        batch_op.drop_column('type')
        batch_op.drop_column('category_id')
        batch_op.drop_column('transaction_time')
        batch_op.drop_column('merchant_name')

    with op.batch_alter_table('user_badges', schema=None) as batch_op:
        batch_op.alter_column('earned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index('idx_user_badges_user_id')
        batch_op.drop_constraint('user_badges_user_id_badge_id_key', type_='unique')
        batch_op.drop_constraint('user_badges_badge_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('user_badges_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'badges', ['badge_id'], ['id'])
        batch_op.create_foreign_key(None, 'user_profiles', ['user_id'], ['id'])

    with op.batch_alter_table('user_course_progress', schema=None) as batch_op:
        batch_op.alter_column('read_articles',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('last_accessed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_constraint('user_course_progress_user_id_course_id_key', type_='unique')
        batch_op.drop_constraint('user_course_progress_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('user_course_progress_course_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['id'])
        batch_op.create_foreign_key(None, 'user_profiles', ['user_id'], ['id'])

    with op.batch_alter_table('user_investment_challenges', schema=None) as batch_op:
        batch_op.alter_column('progress_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
        batch_op.alter_column('started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_constraint('user_investment_challenges_challenge_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('user_investment_challenges_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'investment_challenges', ['challenge_id'], ['id'])
        batch_op.create_foreign_key(None, 'user_profiles', ['user_id'], ['id'])

    with op.batch_alter_table('user_missions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'in_progress'::text"))
        batch_op.alter_column('started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index('idx_user_missions_status')
        batch_op.drop_index('idx_user_missions_user_id')
        batch_op.drop_constraint('user_missions_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('user_missions_mission_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_profiles', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'missions', ['mission_id'], ['id'])

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.alter_column('full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('avatar_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('risk_profile',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('financial_goals',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('preferred_chatbot_persona',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'wise_mentor'::text"))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index('idx_user_profiles_level')
        batch_op.drop_index('idx_user_profiles_total_xp')
        batch_op.drop_constraint('user_profiles_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['id'], ['id'])

    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_constraint('user_settings_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_profiles', ['user_id'], ['id'])

    with op.batch_alter_table('virtual_portfolios', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index('idx_virtual_portfolios_user_id')
        batch_op.drop_constraint('virtual_portfolios_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_profiles', ['user_id'], ['id'])

    with op.batch_alter_table('virtual_positions', schema=None) as batch_op:
        batch_op.alter_column('opened_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('closed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index('idx_virtual_positions_portfolio_id')
        batch_op.drop_index('idx_virtual_positions_status')
        batch_op.drop_constraint('virtual_positions_portfolio_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'virtual_portfolios', ['portfolio_id'], ['id'])

    with op.batch_alter_table('virtual_transactions', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_constraint('virtual_transactions_position_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('virtual_transactions_portfolio_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'virtual_portfolios', ['portfolio_id'], ['id'])
        batch_op.create_foreign_key(None, 'virtual_positions', ['position_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('virtual_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('virtual_transactions_portfolio_id_fkey', 'virtual_portfolios', ['portfolio_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('virtual_transactions_position_id_fkey', 'virtual_positions', ['position_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('virtual_positions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('virtual_positions_portfolio_id_fkey', 'virtual_portfolios', ['portfolio_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('idx_virtual_positions_status', ['status'], unique=False)
        batch_op.create_index('idx_virtual_positions_portfolio_id', ['portfolio_id'], unique=False)
        batch_op.alter_column('closed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('opened_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('virtual_portfolios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('virtual_portfolios_user_id_fkey', 'user_profiles', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('idx_virtual_portfolios_user_id', ['user_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_settings_user_id_fkey', 'user_profiles', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_profiles_id_fkey', 'users', ['id'], ['id'], referent_schema='auth', ondelete='CASCADE')
        batch_op.create_index('idx_user_profiles_total_xp', ['total_xp'], unique=False)
        batch_op.create_index('idx_user_profiles_level', ['level'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('preferred_chatbot_persona',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'wise_mentor'::text"))
        batch_op.alter_column('financial_goals',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
        batch_op.alter_column('risk_profile',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('avatar_url',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('full_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('user_missions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_missions_mission_id_fkey', 'missions', ['mission_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('user_missions_user_id_fkey', 'user_profiles', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('idx_user_missions_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_user_missions_status', ['status'], unique=False)
        batch_op.alter_column('expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('completed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('started_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'in_progress'::text"))

    with op.batch_alter_table('user_investment_challenges', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_investment_challenges_user_id_fkey', 'user_profiles', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('user_investment_challenges_challenge_id_fkey', 'investment_challenges', ['challenge_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('completed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('started_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('progress_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))

    with op.batch_alter_table('user_course_progress', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_course_progress_course_id_fkey', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('user_course_progress_user_id_fkey', 'user_profiles', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint('user_course_progress_user_id_course_id_key', ['user_id', 'course_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('last_accessed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('read_articles',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))

    with op.batch_alter_table('user_badges', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_badges_user_id_fkey', 'user_profiles', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('user_badges_badge_id_fkey', 'badges', ['badge_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint('user_badges_user_id_badge_id_key', ['user_id', 'badge_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_index('idx_user_badges_user_id', ['user_id'], unique=False)
        batch_op.alter_column('earned_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merchant_name', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('transaction_time', postgresql.TIME(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('latitude', sa.NUMERIC(precision=10, scale=8), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('input_method', sa.TEXT(), server_default=sa.text("'manual'::text"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('receipt_image_url', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('transaction_date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('ocr_raw_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.NUMERIC(precision=11, scale=8), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('location', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('transactions_user_id_fkey', 'user_profiles', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('transactions_category_id_fkey', 'categories', ['category_id'], ['id'])
        batch_op.create_index('idx_transactions_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_transactions_user_date', ['user_id', 'transaction_date'], unique=False)
        batch_op.create_index('idx_transactions_type', ['type'], unique=False)
        batch_op.create_index('idx_transactions_date', ['transaction_date'], unique=False)
        batch_op.create_index('idx_transactions_category_id', ['category_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('total_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)
        batch_op.alter_column('transaction_type',
               existing_type=postgresql.ENUM('DEPOSIT', 'WITHDRAWAL', name='transactiontype'),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('spending_patterns', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('spending_patterns_user_id_fkey', 'user_profiles', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint('spending_patterns_user_id_period_start_period_end_period_ty_key', ['user_id', 'period_start', 'period_end', 'period_type'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('ai_recommendations',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('spending_trends',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('top_categories',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('savings_goals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('savings_goals_user_id_fkey', 'users', ['user_id'], ['id'], referent_schema='auth', ondelete='CASCADE')
        batch_op.create_unique_constraint('savings_goals_user_id_key', ['user_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_index('idx_savings_goals_user_id', ['user_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('difficulty',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'easy'::text"))
        batch_op.alter_column('requirement_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('requirement_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('investment_challenges', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('financial_insights', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('financial_insights_user_id_fkey', 'user_profiles', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('idx_financial_insights_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_financial_insights_type', ['type'], unique=False)
        batch_op.create_index('idx_financial_insights_read', ['is_read'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('analysis_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('related_transaction_ids',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('suggested_actions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('content',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('chat_messages_transaction_id_fkey', 'transactions', ['transaction_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('chat_messages_conversation_id_fkey', 'chat_conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('idx_chat_messages_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_chat_messages_conversation_id', ['conversation_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('image_url',
               existing_type=sa.TEXT(),
               comment='URL to the image uploaded by user or generated by AI',
               existing_nullable=True)
        batch_op.alter_column('extracted_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('chat_conversations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('chat_conversations_user_id_fkey', 'user_profiles', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('idx_chat_conversations_user_id', ['user_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('last_message_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('categories_user_id_fkey', 'user_profiles', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint('categories_name_type_user_id_key', ['name', 'type', 'user_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('budgets_user_id_fkey', 'user_profiles', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('budgets_category_id_fkey', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index('idx_budgets_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_budgets_dates', ['start_date', 'end_date'], unique=False)
        batch_op.create_index('idx_budgets_active', ['is_active'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('period',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('requirement_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('rarity',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'common'::text"))
        batch_op.alter_column('category',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('icon',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
