-- Add image_url column to chat_messages table
ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS image_url TEXT;

-- Add comment to document the column
COMMENT ON COLUMN chat_messages.image_url IS 'URL to the image uploaded by user or generated by AI';
